#!/usr/bin/env bash
# Bash script to display username, user ID, and home directory path from /etc/passwd

while IFS=':' read -r username _ uid _ _ home _; do
    echo "$username:$uid:$home"
done < /etc/passwd
