#!/usr/bin/env bash
# Script that displays School 10 times,  but for the 9th iteration, displays Best School and then Hi on a new line
seq=0
while [ $seq -le 9 ]
do
	echo "Best School"
	if [ $seq -eq 8 ]
	then
		echo "Hi"
	fi
	((seq++))
done
