#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and other features
seq=0
while [ $seq -le 9 ]
do
	if [ $seq -eq 3 ]
	then
		echo "bad luck"
	elif [ $seq -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((seq++))
done
